//ADD
const ADD_COFEE_REQUEST = 'ADD_COFEE_REQUEST';
const ADD_COFEE_REQUEST_FAILURE = 'ADD_COFEE_REQUEST_FAILURE';
const ADD_COFEE_REQUEST_SUCCESS = 'ADD_COFEE_REQUEST_SUCCESS';
//GET ONE
const GET_COFEE_REQUEST = 'GET_COFEE_REQUEST';
const GET_COFEE_REQUEST_FAILURE = 'GET_COFEE_REQUEST_FAILURE';
const GET_COFEE_REQUEST_SUCCESS = 'GET_COFEE_REQUEST_SUCCESS';
//GET ALL
const GET_COFEES_REQUEST = 'GET_COFEES_REQUEST';
const GET_COFEES_REQUEST_FAILURE = 'GET_COFEES_REQUEST_FAILURE';
const GET_COFEES_REQUEST_SUCCESS = 'GET_COFEES_REQUEST_SUCCESS';
//REMOVE
const REMOVE_COFEE_REQUEST = 'REMOVE_COFEE_REQUEST';
const REMOVE_COFEE_REQUEST_FAILURE = 'REMOVE_COFEE_REQUEST_FAILURE';
const REMOVE_COFEE_REQUEST_SUCCESS = 'REMOVE_COFEE_REQUEST_SUCCESS';
//UPDATE
const UPDATE_COFEE_REQUEST = 'UPDATE_COFEE_REQUEST';
const UPDATE_COFEE_REQUEST_FAILURE = 'UPDATE_COFEE_REQUEST_FAILURE';
const UPDATE_COFEE_REQUEST_SUCCESS = 'UPDATE_COFEE_REQUEST_SUCCESS';

export {
  ADD_COFEE_REQUEST,
  ADD_COFEE_REQUEST_FAILURE,
  ADD_COFEE_REQUEST_SUCCESS,
  GET_COFEE_REQUEST,
  GET_COFEE_REQUEST_FAILURE,
  GET_COFEE_REQUEST_SUCCESS,
  GET_COFEES_REQUEST,
  GET_COFEES_REQUEST_FAILURE,
  GET_COFEES_REQUEST_SUCCESS,
  REMOVE_COFEE_REQUEST,
  REMOVE_COFEE_REQUEST_FAILURE,
  REMOVE_COFEE_REQUEST_SUCCESS,
  UPDATE_COFEE_REQUEST,
  UPDATE_COFEE_REQUEST_FAILURE,
  UPDATE_COFEE_REQUEST_SUCCESS,
};
